site_name: EarthMiles API Documentation
site_description: OAuth and Partner API documentation
theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - content.code.copy
    
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - OAuth 2.0:
    - Overview: oauth/overview.md
    - Authorization: oauth/authorization.md
    - Token Exchange: oauth/token-exchange.md
  - Partner API:
    - Overview: partner-api/overview.md
    - Rewards API: partner-api/rewards.md
    - Transactions: partner-api/transactions.md
  - Examples:
    - OAuth Flow: examples/oauth-flow.md
    - Partner Integration: examples/partner-integration.md